server:
  port: 8090

domain:
  name: supplyhouse.com

services:
  account-service:
    url: http://localhost:8091
  invitation-service:
    url: http://localhost:8092
  order-service:
    url: http://localhost:8094
