server:
  port: 8092

domain:
  name: supplyhouse.com

services:
    notification-service:
      url: http://localhost:8093
spring:
  datasource:
    url: jdbc:h2:mem:invitationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
